### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by cerus** [cerus/maps#1]
The code is lacking some documentation. This is a nice starter issue if you're kind of new to Open Source or Spigot or just want to work on something simple. (You don't have to comment everything if you don't want to, but it would be nice if you document at least one module.)

Comment if you want to work on this. If you have any questions or need some help feel free to contact me.

**Comment by ameeetgaikwad** [comment]
I would like to help!

**Comment by cerus** [comment]
Hello, thank you for your interest! I just have a quick question: Are you familiar with Java?
