### ISSUE TITLE
Push 3.8.3 to Maven

### ISSUE THREAD

**Issue by cameronbowe** [cerus/maps#10]
### Feature description

Hi, lovely API, but can you release 3.8.3 to Maven? It would never download, and after a quick look, I saw that no maven site is showing 3.8.3 released. I would love 1.20.4 support :)

**Comment by cerus** [comment]
Hello, thanks for reporting this. I'll upload it to Maven Central when I get to my PC. But the only thing that has changed in that version is 1.20 support - if you use the old version in your project but install the latest on your server everything should work.

**Comment by cameronbowe** [comment]
Yeah, I'm aware of that & the fact that it's just for 1.20.4, but I am not uploading it onto the server and instead implementing it into a project that is for 1.20.4. Thanks for taking notice of this though :)

**Comment by cerus** [comment]
3.8.3 is now available from Maven Central
