### ISSUE TITLE
License

### ISSUE THREAD

**Issue by amnoah** [cerus/maps#14]
### Feature description

What license is this project licensed under? I would like to use the library within a GPLv3 project, but I see no license listed so I'm unaware of whether it'll be compatible.

### Relevant issues

_No Response_

**Comment by cerus** [comment]
Hello! The project is licensed under the MIT license, see https://github.com/cerus/maps/blob/main/LICENSE

**Comment by amnoah** [comment]
Oh, I'm sorry that I missed that! I was looking through packet-maps for a while and searched for a license there before coming here as this is the newer project, and apparently my sleep-deprived brain glossed over the license while looking for it.

Thank you for being patient!
